/* JM – Reporting Feed  ·  ONE card, every report level. Filter with report_level.

   GENERATED by scripts/gen_reporting_feed.py — do not hand-edit. Every level
   emits the same 25 columns twice, week and month; the generator writes each
   select list once so the twins cannot drift. Patching this by hand is how the
   month branch of four levels ended up without the GA4 columns.

   READ read_metrics (col G) FIRST — four conversion sources, none interchangeable:
     paid_*  platform-attributed (Meta/Google own pixel, view-through window)
     ga4_*   GA4 last-non-direct session attribution, by session source/medium
     cs_*    Sephora, via catalog segment actions — the ONLY place Sephora
             conversions exist (paid_purchases is ~0 for that whole business)
     site_*  what Shopify actually booked
   paid_roas and ga4_roas will disagree. Show both, never add them.

   GA4 channel mapping: 'metaads / paidsocial' -> Meta, 'google / cpc' -> Google,
   everything else -> 'Other'. TikTok has no mapping yet (no DTC campaigns).
   Google's session_campaign_id is the campaign id; Meta's is <adset_id>_v2_sNN,
   so it needs split_part + an adset->campaign lookup (99.2% resolves).

   Segments come from CAMPAIGN IDs (seeds/campaign_segments.csv), not names.
   Unmapped IDs -> 'Unmapped', reported on the Health rows, never in a total.

   data_valid=FALSE -> the metric rests on data that isn't there (DTC before
   2026-07-27, Sephora before 2025-03). Grey it; don't filter it out.
   has_catalog_feedback=FALSE -> real Sephora spend, conversions unreported. Amber.

   NO template tags on purpose: keeps the card usable by the Gsheet extension
   and as a public CSV. Source of truth: bolt-josiemaran/metabase/01_reporting_feed.sql */
with

wk as (
    /*  Both bounds use the SUNDAY anchor, matching week_start: 'Sunday'.

        `date_trunc('week', current_date)` returns the ISO MONDAY. On Tue 8 Sep
        that is Mon 7 Sep, so `date < '2026-09-07'` fails to exclude the
        Sunday-anchored week beginning 6 Sep — and the report showed a 3-day
        partial week as if it were complete. Spend read -65.5% WoW.

        (date_trunc('week', current_date + 1) - 1) gives the Sunday of the
        current week, so `<` excludes the week in progress.                  */
    select *
    from reporting.josiemaran_blended_performance
    where date_granularity = 'week'
      and date >= (date_trunc('week', current_date + 1) - 1)::date - interval '7 week'
      and date <  (date_trunc('week', current_date + 1) - 1)::date
),

mo as (
    select *
    from reporting.josiemaran_blended_performance
    where date_granularity = 'month'
      and date >= date_trunc('month', current_date) - interval '3 month'
      and date <  date_trunc('month', current_date)
),

dtc_segment as (

    -- Paid DTC Overall = the Meta Overall + Google Overall campaign IDs,
    -- not everything in the DTC account. GA4 is attached by campaign id.
    select
        'DTC Segment'                           as report_level,
        case when grouping(segment) = 1 then 'Paid DTC Overall'
             else segment end                   as row_label,
        'All'                                  as market,
        'week'                                  as grain,
        date                                    as period_start,
        grouping(segment)                       as is_rollup,
        case when grouping(segment) = 1 then 'blended_*' else 'paid_*' end as read_metrics,
        sum(spend)                              as spend,
        sum(impressions)                        as impressions,
        sum(clicks)                             as clicks,
        sum(paid_purchases)                     as paid_purchases,
        sum(paid_revenue)                       as paid_revenue,
        cast(null as double precision)          as cs_purchases,
        cast(null as double precision)          as cs_revenue,
        cast(null as double precision)          as cs_offline_purchases,
        cast(null as double precision)          as cs_add_to_cart,
        sum(ga4_sessions)                       as ga4_sessions,
        sum(ga4_purchases)                      as ga4_purchases,
        sum(ga4_revenue)                        as ga4_revenue,
        sum(shopify_orders)                     as site_orders,
        sum(shopify_first_orders)               as site_first_orders,
        sum(shopify_new_customers)              as site_new_customers,
        sum(shopify_gross_sales)                as site_gross_sales,
        cast(null as varchar(8))                as status,
        cast(null as varchar(256))              as detail
    from wk
    where business_line = 'DTC'
      and (in_dtc_overall or channel = 'Shopify')
    group by grouping sets ((date), (date, segment))
    having sum(spend) > 0 or sum(shopify_orders) > 0

    union all

    select
        'DTC Segment'                           as report_level,
        case when grouping(segment) = 1 then 'Paid DTC Overall'
             else segment end                   as row_label,
        'All'                                  as market,
        'month'                                  as grain,
        date                                    as period_start,
        grouping(segment)                       as is_rollup,
        case when grouping(segment) = 1 then 'blended_*' else 'paid_*' end as read_metrics,
        sum(spend)                              as spend,
        sum(impressions)                        as impressions,
        sum(clicks)                             as clicks,
        sum(paid_purchases)                     as paid_purchases,
        sum(paid_revenue)                       as paid_revenue,
        cast(null as double precision)          as cs_purchases,
        cast(null as double precision)          as cs_revenue,
        cast(null as double precision)          as cs_offline_purchases,
        cast(null as double precision)          as cs_add_to_cart,
        sum(ga4_sessions)                       as ga4_sessions,
        sum(ga4_purchases)                      as ga4_purchases,
        sum(ga4_revenue)                        as ga4_revenue,
        sum(shopify_orders)                     as site_orders,
        sum(shopify_first_orders)               as site_first_orders,
        sum(shopify_new_customers)              as site_new_customers,
        sum(shopify_gross_sales)                as site_gross_sales,
        cast(null as varchar(8))                as status,
        cast(null as varchar(256))              as detail
    from mo
    where business_line = 'DTC'
      and (in_dtc_overall or channel = 'Shopify')
    group by grouping sets ((date), (date, segment))
    having sum(spend) > 0 or sum(shopify_orders) > 0

),

sephora_segment as (

    -- Meta AND TikTok. No ga4_* — GA4 measures josiemaran.com, and
    -- Sephora traffic leaves the site, so GA4 never sees the purchase.
    select
        'Sephora Segment'                       as report_level,
        case when grouping(segment) = 1 and grouping(market) = 0
                  then 'Sephora – ' || market
             when grouping(segment) = 1 then 'Sephora – Total'
             else segment end                   as row_label,
        coalesce(market, 'All')                                  as market,
        'week'                                  as grain,
        date                                    as period_start,
        grouping(segment)                       as is_rollup,
        'cs_*' as read_metrics,
        sum(spend)                              as spend,
        sum(impressions)                        as impressions,
        sum(clicks)                             as clicks,
        cast(null as double precision)          as paid_purchases,
        cast(null as double precision)          as paid_revenue,
        sum(cs_purchases)                       as cs_purchases,
        sum(cs_revenue)                         as cs_revenue,
        sum(cs_offline_purchases)               as cs_offline_purchases,
        sum(cs_add_to_cart)                     as cs_add_to_cart,
        cast(null as bigint)                    as ga4_sessions,
        cast(null as double precision)          as ga4_purchases,
        cast(null as double precision)          as ga4_revenue,
        cast(null as bigint)                    as site_orders,
        cast(null as bigint)                    as site_first_orders,
        cast(null as bigint)                    as site_new_customers,
        cast(null as double precision)          as site_gross_sales,
        cast(null as varchar(8))                as status,
        cast(null as varchar(256))              as detail
    from wk
    where business_line = 'Sephora'
    group by grouping sets ((date), (date, market), (date, segment))
    having sum(spend) > 0

    union all

    select
        'Sephora Segment'                       as report_level,
        case when grouping(segment) = 1 and grouping(market) = 0
                  then 'Sephora – ' || market
             when grouping(segment) = 1 then 'Sephora – Total'
             else segment end                   as row_label,
        coalesce(market, 'All')                                  as market,
        'month'                                  as grain,
        date                                    as period_start,
        grouping(segment)                       as is_rollup,
        'cs_*' as read_metrics,
        sum(spend)                              as spend,
        sum(impressions)                        as impressions,
        sum(clicks)                             as clicks,
        cast(null as double precision)          as paid_purchases,
        cast(null as double precision)          as paid_revenue,
        sum(cs_purchases)                       as cs_purchases,
        sum(cs_revenue)                         as cs_revenue,
        sum(cs_offline_purchases)               as cs_offline_purchases,
        sum(cs_add_to_cart)                     as cs_add_to_cart,
        cast(null as bigint)                    as ga4_sessions,
        cast(null as double precision)          as ga4_purchases,
        cast(null as double precision)          as ga4_revenue,
        cast(null as bigint)                    as site_orders,
        cast(null as bigint)                    as site_first_orders,
        cast(null as bigint)                    as site_new_customers,
        cast(null as double precision)          as site_gross_sales,
        cast(null as varchar(8))                as status,
        cast(null as varchar(256))              as detail
    from mo
    where business_line = 'Sephora'
    group by grouping sets ((date), (date, market), (date, segment))
    having sum(spend) > 0

),

campaign as (

    -- Both conversion families side by side; read_metrics says which applies.
    select
        'Campaign'                              as report_level,
        campaign_id || '  ·  ' || coalesce(campaign_name, '(no name)')                   as row_label,
        market                                  as market,
        'week'                                  as grain,
        date                                    as period_start,
        0                       as is_rollup,
        case when business_line = 'Sephora' then 'cs_*' else 'paid_*' end as read_metrics,
        sum(spend)                              as spend,
        sum(impressions)                        as impressions,
        sum(clicks)                             as clicks,
        sum(paid_purchases)                     as paid_purchases,
        sum(paid_revenue)                       as paid_revenue,
        sum(cs_purchases)                       as cs_purchases,
        sum(cs_revenue)                         as cs_revenue,
        sum(cs_offline_purchases)               as cs_offline_purchases,
        sum(cs_add_to_cart)                     as cs_add_to_cart,
        sum(ga4_sessions)                       as ga4_sessions,
        sum(ga4_purchases)                      as ga4_purchases,
        sum(ga4_revenue)                        as ga4_revenue,
        cast(null as bigint)                    as site_orders,
        cast(null as bigint)                    as site_first_orders,
        cast(null as bigint)                    as site_new_customers,
        cast(null as double precision)          as site_gross_sales,
        cast(null as varchar(8))                as status,
        cast(null as varchar(256))              as detail
    from wk
    where channel not in ('Shopify', 'GA4')
      and campaign_id is not null
    group by campaign_id, campaign_name, market, date, business_line, segment
    having sum(spend) > 0

    union all

    select
        'Campaign'                              as report_level,
        campaign_id || '  ·  ' || coalesce(campaign_name, '(no name)')                   as row_label,
        market                                  as market,
        'month'                                  as grain,
        date                                    as period_start,
        0                       as is_rollup,
        case when business_line = 'Sephora' then 'cs_*' else 'paid_*' end as read_metrics,
        sum(spend)                              as spend,
        sum(impressions)                        as impressions,
        sum(clicks)                             as clicks,
        sum(paid_purchases)                     as paid_purchases,
        sum(paid_revenue)                       as paid_revenue,
        sum(cs_purchases)                       as cs_purchases,
        sum(cs_revenue)                         as cs_revenue,
        sum(cs_offline_purchases)               as cs_offline_purchases,
        sum(cs_add_to_cart)                     as cs_add_to_cart,
        sum(ga4_sessions)                       as ga4_sessions,
        sum(ga4_purchases)                      as ga4_purchases,
        sum(ga4_revenue)                        as ga4_revenue,
        cast(null as bigint)                    as site_orders,
        cast(null as bigint)                    as site_first_orders,
        cast(null as bigint)                    as site_new_customers,
        cast(null as double precision)          as site_gross_sales,
        cast(null as varchar(8))                as status,
        cast(null as varchar(256))              as detail
    from mo
    where channel not in ('Shopify', 'GA4')
      and campaign_id is not null
    group by campaign_id, campaign_name, market, date, business_line, segment
    having sum(spend) > 0

),

ga4_channel as (

    -- GA4 rows with no paid campaign to attach to: 'Other' (email, SMS,
    -- organic, direct, affiliates) and 'Unattributed Paid'. Surfacing them
    -- means total GA4 revenue reconciles to the raw table.
    select
        'GA4 Channel'                           as report_level,
        segment                   as row_label,
        'All'                                  as market,
        'week'                                  as grain,
        date                                    as period_start,
        0                       as is_rollup,
        'ga4_*' as read_metrics,
        cast(null as double precision)          as spend,
        cast(null as bigint)                    as impressions,
        cast(null as double precision)          as clicks,
        cast(null as double precision)          as paid_purchases,
        cast(null as double precision)          as paid_revenue,
        cast(null as double precision)          as cs_purchases,
        cast(null as double precision)          as cs_revenue,
        cast(null as double precision)          as cs_offline_purchases,
        cast(null as double precision)          as cs_add_to_cart,
        sum(ga4_sessions)                       as ga4_sessions,
        sum(ga4_purchases)                      as ga4_purchases,
        sum(ga4_revenue)                        as ga4_revenue,
        cast(null as bigint)                    as site_orders,
        cast(null as bigint)                    as site_first_orders,
        cast(null as bigint)                    as site_new_customers,
        cast(null as double precision)          as site_gross_sales,
        cast(null as varchar(8))                as status,
        cast(null as varchar(256))              as detail
    from wk
    where channel = 'GA4'
    group by segment, date
    having sum(ga4_sessions) > 0

    union all

    select
        'GA4 Channel'                           as report_level,
        segment                   as row_label,
        'All'                                  as market,
        'month'                                  as grain,
        date                                    as period_start,
        0                       as is_rollup,
        'ga4_*' as read_metrics,
        cast(null as double precision)          as spend,
        cast(null as bigint)                    as impressions,
        cast(null as double precision)          as clicks,
        cast(null as double precision)          as paid_purchases,
        cast(null as double precision)          as paid_revenue,
        cast(null as double precision)          as cs_purchases,
        cast(null as double precision)          as cs_revenue,
        cast(null as double precision)          as cs_offline_purchases,
        cast(null as double precision)          as cs_add_to_cart,
        sum(ga4_sessions)                       as ga4_sessions,
        sum(ga4_purchases)                      as ga4_purchases,
        sum(ga4_revenue)                        as ga4_revenue,
        cast(null as bigint)                    as site_orders,
        cast(null as bigint)                    as site_first_orders,
        cast(null as bigint)                    as site_new_customers,
        cast(null as double precision)          as site_gross_sales,
        cast(null as varchar(8))                as status,
        cast(null as varchar(256))              as detail
    from mo
    where channel = 'GA4'
    group by segment, date
    having sum(ga4_sessions) > 0

),

site as (

    -- Web vs Subscription is the split that decides whether a blended
    -- number means anything: 21% of orders are subscription renewals.
    select
        'Site'                                  as report_level,
        coalesce(order_type, 'All')                   as row_label,
        coalesce(market, 'All')                                  as market,
        'week'                                  as grain,
        date                                    as period_start,
        grouping(order_type)                       as is_rollup,
        'site_*' as read_metrics,
        cast(null as double precision)          as spend,
        cast(null as bigint)                    as impressions,
        cast(null as double precision)          as clicks,
        cast(null as double precision)          as paid_purchases,
        cast(null as double precision)          as paid_revenue,
        cast(null as double precision)          as cs_purchases,
        cast(null as double precision)          as cs_revenue,
        cast(null as double precision)          as cs_offline_purchases,
        cast(null as double precision)          as cs_add_to_cart,
        cast(null as bigint)                    as ga4_sessions,
        cast(null as double precision)          as ga4_purchases,
        cast(null as double precision)          as ga4_revenue,
        sum(shopify_orders)                     as site_orders,
        sum(shopify_first_orders)               as site_first_orders,
        sum(shopify_new_customers)              as site_new_customers,
        sum(shopify_gross_sales)                as site_gross_sales,
        cast(null as varchar(8))                as status,
        cast(null as varchar(256))              as detail
    from wk
    where channel = 'Shopify'
    group by grouping sets ((date), (date, order_type), (date, market))
    having sum(shopify_orders) > 0

    union all

    select
        'Site'                                  as report_level,
        coalesce(order_type, 'All')                   as row_label,
        coalesce(market, 'All')                                  as market,
        'month'                                  as grain,
        date                                    as period_start,
        grouping(order_type)                       as is_rollup,
        'site_*' as read_metrics,
        cast(null as double precision)          as spend,
        cast(null as bigint)                    as impressions,
        cast(null as double precision)          as clicks,
        cast(null as double precision)          as paid_purchases,
        cast(null as double precision)          as paid_revenue,
        cast(null as double precision)          as cs_purchases,
        cast(null as double precision)          as cs_revenue,
        cast(null as double precision)          as cs_offline_purchases,
        cast(null as double precision)          as cs_add_to_cart,
        cast(null as bigint)                    as ga4_sessions,
        cast(null as double precision)          as ga4_purchases,
        cast(null as double precision)          as ga4_revenue,
        sum(shopify_orders)                     as site_orders,
        sum(shopify_first_orders)               as site_first_orders,
        sum(shopify_new_customers)              as site_new_customers,
        sum(shopify_gross_sales)                as site_gross_sales,
        cast(null as varchar(8))                as status,
        cast(null as varchar(256))              as detail
    from mo
    where channel = 'Shopify'
    group by grouping sets ((date), (date, order_type), (date, market))
    having sum(shopify_orders) > 0

),

health_freshness as (
    select
        channel                                 as subject,
        'freshness'                             as check_name,
        max(date)::varchar || ' · '
            || datediff(day, max(date), current_date)::varchar || 'd behind' as detail,
        case when datediff(day, max(date), current_date) > 3 then 'FAIL' else 'OK' end as status
    from reporting.josiemaran_blended_performance
    where date_granularity = 'day'
    group by 1
),

health_catalog as (
    select
        segment                                 as subject,
        'catalog-feedback'                      as check_name,
        round(100.0 * sum(case when coalesce(cs_purchases,0) = 0 then spend else 0 end)
                    / nullif(sum(spend),0), 1)::varchar || '% of $'
            || round(sum(spend))::varchar || ' unmeasured'  as detail,
        case when sum(case when coalesce(cs_purchases,0) = 0 then spend else 0 end)
                / nullif(sum(spend),0) > 0.20 then 'FAIL' else 'OK' end as status
    from reporting.josiemaran_blended_performance
    where date_granularity = 'day' and business_line = 'Sephora'
      and date >= dateadd(day, -30, current_date)
    group by 1
),

health_mapping as (
    -- 7-day window on purpose: the nine predecessors of the current structure
    -- all stopped spending by 2026-08-27, so a 30-day window reports ~$44k of
    -- correctly-unmapped retired spend and fails through the whole transition.
    select
        'Unmapped campaign IDs (7d)'            as subject,
        'mapping'                               as check_name,
        '$' || round(sum(case when segment = 'Unmapped' then spend else 0 end))::varchar
            || ' of $' || round(sum(spend))::varchar
            || ' · ' || count(distinct case when segment = 'Unmapped' then campaign_id end)::varchar
            || ' campaign(s)'                   as detail,
        case when sum(case when segment = 'Unmapped' then spend else 0 end) > 500
             then 'FAIL' else 'OK' end          as status
    from reporting.josiemaran_blended_performance
    where date_granularity = 'day' and channel not in ('Shopify', 'GA4')
      and date >= dateadd(day, -7, current_date)

    union all

    select
        'NULL campaign_id (7d)', 'mapping',
        '$' || round(sum(case when campaign_id is null then spend else 0 end))::varchar
            || ' of $' || round(sum(spend))::varchar,
        case when sum(case when campaign_id is null then spend else 0 end) > 0
             then 'FAIL' else 'OK' end
    from reporting.josiemaran_blended_performance
    where date_granularity = 'day' and channel not in ('Shopify', 'GA4')
      and date >= dateadd(day, -7, current_date)
),

health_ga4 as (
    -- GA4 revenue that attached to no paid campaign, as a share of all GA4
    -- revenue. High is normal (email/SMS/organic are most of it); a sudden
    -- jump means the Meta adset->campaign lookup has started failing.
    select
        'GA4 unattributed share (7d)'           as subject,
        'ga4'                                   as check_name,
        round(100.0 * sum(case when segment = 'Unattributed Paid' then ga4_revenue else 0 end)
                    / nullif(sum(ga4_revenue), 0), 1)::varchar || '% of paid-source GA4 revenue'
                                                as detail,
        case when sum(case when segment = 'Unattributed Paid' then ga4_revenue else 0 end)
                / nullif(sum(ga4_revenue), 0) > 0.15 then 'FAIL' else 'OK' end as status
    from reporting.josiemaran_blended_performance
    where date_granularity = 'day' and channel = 'GA4'
      and date >= dateadd(day, -7, current_date)
),

health_zero as (
    select
        business_line || ' – ' || channel        as subject,
        'zero-conversion'                        as check_name,
        '$' || round(sum(spend))::varchar || ' · '
            || round(sum(coalesce(paid_purchases,0)) + sum(coalesce(cs_purchases,0)))::varchar
            || ' conversions (30d)'              as detail,
        case when sum(spend) > 1000
              and sum(coalesce(paid_purchases,0)) + sum(coalesce(cs_purchases,0)) = 0
             then 'FAIL' else 'OK' end           as status
    from reporting.josiemaran_blended_performance
    where date_granularity = 'day' and channel not in ('Shopify', 'GA4')
      and date >= dateadd(day, -30, current_date)
    group by 1
),

health as (
    select
        'Health'                                as report_level,
        check_name || ': ' || subject           as row_label,
        'All'                                   as market,
        'n/a'                                   as grain,
        current_date                            as period_start,
        0                                       as is_rollup,
        'status'                                as read_metrics,
        cast(null as double precision)          as spend,
        cast(null as bigint)                    as impressions,
        cast(null as double precision)          as clicks,
        cast(null as double precision)          as paid_purchases,
        cast(null as double precision)          as paid_revenue,
        cast(null as double precision)          as cs_purchases,
        cast(null as double precision)          as cs_revenue,
        cast(null as double precision)          as cs_offline_purchases,
        cast(null as double precision)          as cs_add_to_cart,
        cast(null as bigint)                    as ga4_sessions,
        cast(null as double precision)          as ga4_purchases,
        cast(null as double precision)          as ga4_revenue,
        cast(null as bigint)                    as site_orders,
        cast(null as bigint)                    as site_first_orders,
        cast(null as bigint)                    as site_new_customers,
        cast(null as double precision)          as site_gross_sales,
        status,
        detail
    from (
        select * from health_freshness
        union all select * from health_catalog
        union all select * from health_mapping
        union all select * from health_ga4
        union all select * from health_zero
    ) h
),

unioned as (
    select * from dtc_segment
    union all select * from sephora_segment
    union all select * from campaign
    union all select * from ga4_channel
    union all select * from site
    union all select * from health
)

select
    report_level,
    row_label,
    market,
    grain,
    case grain when 'week'  then to_char(period_start, 'IYYY-"W"IW')
               when 'month' then to_char(period_start, 'YYYY-MM')
               else '' end                                      as period_label,
    period_start,
    read_metrics,

    report_level || '|' || row_label || '|' || market || '|' ||
        case grain when 'week'  then to_char(period_start, 'IYYY-"W"IW')
                   when 'month' then to_char(period_start, 'YYYY-MM')
                   else '' end                                  as lookup_key,

    -- ── Delivery ───────────────────────────────────────────────────────────
    round(spend, 2)                                             as spend,
    impressions,
    round(clicks, 0)                                            as clicks,
    case when impressions > 0 then round(spend / impressions * 1000, 2) end     as cpm,
    case when impressions > 0 then round(clicks::numeric / impressions, 4) end  as ctr,
    case when clicks      > 0 then round(spend / clicks, 2) end                 as cpc,

    -- ── Platform-attributed ────────────────────────────────────────────────
    round(paid_purchases, 0)                                    as paid_purchases,
    round(paid_revenue, 2)                                       as paid_revenue,
    case when spend          > 0 then round(paid_revenue / spend, 2) end        as paid_roas,
    case when paid_purchases > 0 then round(spend / paid_purchases, 2) end      as paid_cpa,
    case when clicks         > 0 then round(paid_purchases::numeric / clicks, 4) end as paid_cvr,
    case when paid_purchases > 0 then round(paid_revenue / paid_purchases, 2) end as paid_aov,

    -- ── GA4 ────────────────────────────────────────────────────────────────
    ga4_sessions,
    round(ga4_purchases, 0)                                      as ga4_purchases,
    round(ga4_revenue, 2)                                        as ga4_revenue,
    case when spend         > 0 then round(ga4_revenue / spend, 2) end          as ga4_roas,
    case when ga4_purchases > 0 then round(spend / ga4_purchases, 2) end        as ga4_cpa,
    case when ga4_purchases > 0 then round(ga4_revenue / ga4_purchases, 2) end  as ga4_aov,
    case when ga4_sessions  > 0 then round(ga4_purchases::numeric / ga4_sessions, 4) end as ga4_cvr,

    -- ── Sephora catalog segment ────────────────────────────────────────────
    round(cs_purchases, 0)                                       as cs_purchases,
    round(cs_revenue, 2)                                         as cs_revenue,
    case when spend        > 0 then round(cs_revenue / spend, 2) end            as cs_roas,
    case when cs_purchases > 0 then round(spend / cs_purchases, 2) end          as cs_cpa,
    case when cs_purchases > 0 then round(cs_revenue / cs_purchases, 2) end     as cs_aov,
    case when clicks       > 0 then round(cs_purchases::numeric / clicks, 4) end as cs_cvr,
    round(cs_add_to_cart, 0)                                     as cs_add_to_cart,
    round(cs_offline_purchases, 0)                               as cs_instore_purchases,
    case when cs_purchases > 0
         then round(cs_offline_purchases::numeric / cs_purchases, 4) end        as pct_instore,

    -- ── Site ───────────────────────────────────────────────────────────────
    site_orders,
    site_first_orders,
    site_new_customers,
    round(site_gross_sales, 2)                                   as site_gross_sales,
    case when site_orders > 0 then round(site_gross_sales / site_orders, 2) end            as aov,
    case when site_orders > 0 then round(site_first_orders::numeric / site_orders, 4) end  as pct_new,

    -- ── Blended: rollup rows only ──────────────────────────────────────────
    case when is_rollup = 1 and spend > 0 and site_gross_sales > 0
         then round(site_gross_sales / spend, 2) end              as blended_roas,
    case when is_rollup = 1 and spend > 0 and site_new_customers > 0
         then round(spend / site_new_customers, 2) end            as blended_cac,

    -- ── Flags ──────────────────────────────────────────────────────────────
    case
        when report_level = 'Health'          then true
        when report_level = 'Sephora Segment' then period_start >= '2025-03-01'
        when report_level = 'GA4 Channel'     then period_start >= '2024-08-17'
        when grain = 'month'                   then period_start >= '2026-08-01'
        else period_start >= '2026-07-27'
    end                                                          as data_valid,

    case when read_metrics = 'cs_*'
         then coalesce(cs_purchases, 0) > 0 or coalesce(cs_add_to_cart, 0) > 0
    end                                                          as has_catalog_feedback,

    status,
    detail

from unioned
order by
    case report_level when 'Health' then 0 when 'DTC Segment' then 1
         when 'Sephora Segment' then 2 when 'GA4 Channel' then 3
         when 'Site' then 4 else 5 end,
    period_start desc,
    is_rollup desc,
    spend desc nulls last,
    row_label
