#!/usr/bin/env python3
"""
Compile the Gsheet cards' models into standalone Metabase queries, and render
their dbt tests so they can be run.

    python3 scripts/build_sheet_cards.py            # writes the standalone cards
    python3 scripts/build_sheet_cards.py --tests D  # also renders the dbt tests into dir D

Cards (one model + one parameter-free Metabase SELECT over it):
    budget_pacing        metabase/02_budget_pacing.sql        Budget Pacing, DoD Budgets tabs
    dtc_sales_vs_spend   metabase/03_dtc_sales_vs_spend.sql   Gross Sales vs Spend tab

Why this exists
---------------
dbt is not installed where this repo is worked on, and a card has to be wired up
and checked before the scheduled dbt run has built its table. This renders each
model (macros expanded, ref()/source()/var() resolved) into CTEs over tables that
exist today and puts the card's SELECT on top, exactly as build_standalone_feed.py
does for the reporting feed.

It reuses that script's renderer rather than copying it, so the two cannot
disagree on how a macro or a source is expanded. It is a GENERATOR: each card is
derived from its model file, so interim and post-dbt numbers cannot drift.

AFTER `dbt run`: point the Metabase question at the card's own SQL file in
metabase/ (the same final SELECT over the real table) and delete the generated one.
"""
import importlib.util, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

spec = importlib.util.spec_from_file_location("bsf", ROOT / "scripts" / "build_standalone_feed.py")
bsf = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bsf)

# Teach the shared renderer what these models add. Mutated in this process only;
# build_standalone_feed.py itself is untouched.
bsf.VARS.setdefault("time_zone", "US/Eastern")
bsf.SOURCE_SCHEMAS["gsheet_budget_raw"] = "gsheet_raw"
# These are real, already-built tables; read them, don't recompile their lineage.
bsf.BASE_TABLES["blended_performance"] = f"reporting.{bsf.DB}_blended_performance"
bsf.BASE_TABLES["shopify_sales_by_segment"] = f"reporting.{bsf.DB}_shopify_sales_by_segment"
# The models themselves resolve to a CTE of the same name, which only matters when a
# TEST refs them (a test is rendered over the model it checks).
bsf.BASE_TABLES["budget_pacing"] = "budget_pacing"
bsf.BASE_TABLES["dtc_sales_vs_spend"] = "dtc_sales_vs_spend"

CARDS = [
    {"model": "budget_pacing",
     "card": "02_budget_pacing.sql",
     "title": "JM – Budget Pacing",
     "reads": [f"reporting.{bsf.DB}_blended_performance", "gsheet_raw.josie_maran_budget_forecast"],
     "tests": ["assert_budget_lines_mapped", "assert_budget_pacing_spend_ties_to_blended"]},
    {"model": "dtc_sales_vs_spend",
     "card": "03_dtc_sales_vs_spend.sql",
     "title": "JM – DTC Sales vs Spend",
     "reads": [f"reporting.{bsf.DB}_blended_performance",
               f"reporting.{bsf.DB}_shopify_sales_by_segment"],
     "tests": ["assert_dtc_spend_is_classified", "assert_dtc_sales_vs_spend_ties_to_sources"]},
]


def table_of(card):
    return f"reporting.{bsf.DB}_{card['model']}"


def model_ctes(macros, model):
    """The model as [(cte_name, body)] plus a final SELECT, CTE names namespaced."""
    body, had_with = bsf.render_model(model, macros)
    assert had_with, f"{model} is expected to open with its own WITH"
    body = re.sub(r"\n{3,}", "\n\n", body)
    inner, final = bsf.split_last_select(body)
    return bsf.prefix_ctes(inner, final, model)


def strip_sql_comments(sql):
    sql = re.sub(r"/\*.*?\*/", "", sql, flags=re.S)
    sql = re.sub(r"^\s*--.*$", "", sql, flags=re.M)
    return re.sub(r"\n{3,}", "\n\n", sql).strip()


def card_select(card):
    sql = strip_sql_comments((ROOT / "metabase" / card["card"]).read_text())
    if table_of(card) not in sql:
        sys.exit(f"metabase/{card['card']} no longer reads {table_of(card)}")
    return sql.replace(table_of(card), card["model"])


def cte_parts(macros, card):
    inner, final = model_ctes(macros, card["model"])
    parts = [f"{nm} as (\n{bd.strip()}\n)" for nm, bd in inner]
    parts.append(f"{card['model']} as (\n{final.strip()}\n)")
    return parts


def standalone(macros, card):
    reads = "\n  ".join(card["reads"])
    header = f"""/*
  {card['title']}  ·  STANDALONE (pre-dbt) build
  ══════════════════════════════════════════════════════════════════════════════
  GENERATED by scripts/build_sheet_cards.py — do not hand-edit.
  Edit models/reporting/{card['model']}.sql or metabase/{card['card']} and re-run.

  Same model logic as the dbt table, compiled over tables that exist today:
  {reads}
  so the Gsheet can be wired up before `dbt run` has built {table_of(card)}.

  AFTER `dbt run`: point the Metabase question at metabase/{card['card']}
  and delete this file.
*/

with
"""
    return header + ",\n\n".join(cte_parts(macros, card)) + "\n\n" + card_select(card) + "\n"


def render_test(name, macros, card):
    """A dbt test rendered over its model's CTEs, as runnable SQL (rows returned = failure)."""
    body, had_with = bsf.render_model(f"../../tests/{name}", macros)
    return "with\n" + ",\n\n".join(cte_parts(macros, card)) + (",\n\n" if had_with else "\n\n") + body.strip() + "\n"


def main():
    macros = bsf.load_macros()
    for needed in ("jm_budget_campaigns", "jm_budget_keys"):
        if needed not in macros:
            sys.exit(f"macro {needed} not found — run scripts/gen_budget_map_macro.py first")

    for card in CARDS:
        out = standalone(macros, card)
        dest = ROOT / "metabase" / "generated" / f"{pathlib.Path(card['card']).stem}_standalone.sql"
        dest.write_text(out)
        print(f"wrote {dest.relative_to(ROOT)}  ({len(out):,} chars, {out.count(chr(10)):,} lines)")

    if "--tests" in sys.argv:
        tdir = pathlib.Path(sys.argv[sys.argv.index("--tests") + 1])
        tdir.mkdir(parents=True, exist_ok=True)
        for card in CARDS:
            for t in card["tests"]:
                (tdir / f"{t}.sql").write_text(render_test(t, macros, card))
                print(f"wrote {tdir / (t + '.sql')}")


if __name__ == "__main__":
    main()
