#!/usr/bin/env python3
"""
Compile budget_pacing into a standalone Metabase query, and render its tests.

    python3 scripts/build_pacing_card.py            # writes the standalone card
    python3 scripts/build_pacing_card.py --tests D  # also renders the dbt tests into dir D

Why this exists
---------------
dbt is not installed where this repo is worked on, and the card has to be
wired up and checked before the scheduled dbt run has built
reporting.josiemaran_budget_pacing. This renders the model (macros expanded,
ref()/source()/var() resolved) into CTEs over tables that exist today and puts
the card's SELECT on top, exactly as build_standalone_feed.py does for the feed.

It reuses that script's renderer rather than copying it, so the two cannot
disagree on how a macro or a source is expanded. It is a GENERATOR: the card is
derived from the model file, so interim and post-dbt numbers cannot drift.

AFTER `dbt run`: point the Metabase question at metabase/02_budget_pacing.sql
(the same final SELECT over the real table) and delete the generated file.
"""
import importlib.util, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

spec = importlib.util.spec_from_file_location("bsf", ROOT / "scripts" / "build_standalone_feed.py")
bsf = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bsf)

# Teach the shared renderer the three things this model adds. Mutated in this
# process only; build_standalone_feed.py itself is untouched.
bsf.VARS.setdefault("time_zone", "US/Eastern")
bsf.SOURCE_SCHEMAS["gsheet_budget_raw"] = "gsheet_raw"
# blended_performance is a real, already-built table; read it, don't recompile it.
bsf.BASE_TABLES["blended_performance"] = f"reporting.{bsf.DB}_blended_performance"
# Only used when rendering the tests, which ref() the model: it becomes a CTE.
bsf.BASE_TABLES["budget_pacing"] = "budget_pacing"

CARD_TABLE = f"reporting.{bsf.DB}_budget_pacing"


def model_ctes(macros):
    """The model as [(cte_name, body)] plus a final SELECT, CTE names namespaced."""
    body, had_with = bsf.render_model("budget_pacing", macros)
    assert had_with, "budget_pacing is expected to open with its own WITH"
    body = re.sub(r"\n{3,}", "\n\n", body)
    inner, final = bsf.split_last_select(body)
    return bsf.prefix_ctes(inner, final, "budget_pacing")


def strip_sql_comments(sql):
    sql = re.sub(r"/\*.*?\*/", "", sql, flags=re.S)
    sql = re.sub(r"^\s*--.*$", "", sql, flags=re.M)
    return re.sub(r"\n{3,}", "\n\n", sql).strip()


def card_select():
    sql = strip_sql_comments((ROOT / "metabase" / "02_budget_pacing.sql").read_text())
    if CARD_TABLE not in sql:
        sys.exit(f"metabase/02_budget_pacing.sql no longer reads {CARD_TABLE}")
    return sql.replace(CARD_TABLE, "budget_pacing")


def standalone(macros):
    inner, final = model_ctes(macros)
    parts = [f"{nm} as (\n{bd.strip()}\n)" for nm, bd in inner]
    parts.append(f"budget_pacing as (\n{final.strip()}\n)")
    header = f"""/*
  JM – Budget Pacing  ·  STANDALONE (pre-dbt) build
  ══════════════════════════════════════════════════════════════════════════════
  GENERATED by scripts/build_pacing_card.py — do not hand-edit.
  Edit models/reporting/budget_pacing.sql or metabase/02_budget_pacing.sql and
  re-run.

  Same model logic as the dbt table, compiled over tables that exist today
  ({CARD_TABLE.split('.')[0]}.{bsf.DB}_blended_performance and
  gsheet_raw.josie_maran_budget_forecast), so the Gsheet can be wired up before
  `dbt run` has built reporting.{bsf.DB}_budget_pacing.

  AFTER `dbt run`: point the Metabase question at metabase/02_budget_pacing.sql
  and delete this file.
*/

with
"""
    return header + ",\n\n".join(parts) + "\n\n" + card_select() + "\n"


def render_test(name, macros):
    """A dbt test rendered over the model CTEs, as runnable SQL (rows returned = failure)."""
    inner, final = model_ctes(macros)
    body, had_with = bsf.render_model(f"../../tests/{name}", macros)
    parts = [f"{nm} as (\n{bd.strip()}\n)" for nm, bd in inner]
    parts.append(f"budget_pacing as (\n{final.strip()}\n)")
    if had_with:
        # the test opens with its own CTEs: append them to the same WITH list
        return "with\n" + ",\n\n".join(parts) + ",\n\n" + body.strip() + "\n"
    return "with\n" + ",\n\n".join(parts) + "\n\n" + body.strip() + "\n"


def main():
    macros = bsf.load_macros()
    for needed in ("jm_budget_campaigns", "jm_budget_keys"):
        if needed not in macros:
            sys.exit(f"macro {needed} not found — run scripts/gen_budget_map_macro.py first")

    out = standalone(macros)
    dest = ROOT / "metabase" / "generated" / "02_budget_pacing_standalone.sql"
    dest.write_text(out)
    print(f"wrote {dest.relative_to(ROOT)}  ({len(out):,} chars, {out.count(chr(10)):,} lines)")

    if "--tests" in sys.argv:
        tdir = pathlib.Path(sys.argv[sys.argv.index("--tests") + 1])
        tdir.mkdir(parents=True, exist_ok=True)
        for t in ("assert_budget_lines_mapped", "assert_budget_pacing_spend_ties_to_blended"):
            (tdir / f"{t}.sql").write_text(render_test(t, macros))
            print(f"wrote {tdir / (t + '.sql')}")


if __name__ == "__main__":
    main()
